[env:esp32-c3-super-mini]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
monitor_speed = 115200
build_flags = 
	-DARDUINO_USB_CDC_ON_BOOT=1
	-DARDUINO_USB_MODE=1
lib_deps = 
	links2004/WebSockets@^2.7.3
	nanopb/Nanopb@^0.4.91
	adafruit/Adafruit GFX Library@^1.12.6
	adafruit/Adafruit ST7735 and ST7789 Library@^1.11.0
